[package]
name = "nancywebdebug"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
default-run = "nancywebdebug"

[dependencies]
base64 = "0.22.1"
bytes = "1.10.1"
brotli = "8.0.2"
clap = { version = "4.5.47", features = ["derive"] }
encoding_rs = "0.8.35"
eframe = "0.31.1"
flate2 = "1.1.2"
futures-util = "0.3.31"
h3 = "0.0.8"
h3-quinn = "0.0.10"
hickory-resolver = "0.26.1"
http = "1.3.1"
http-body-util = "0.1.3"
hyper = { version = "1.6.0", features = ["client", "http1", "http2"] }
hyper-util = { version = "0.1.14", features = ["tokio"] }
markup_fmt = "0.27.3"
oauth2 = { version = "5.0.0", default-features = false }
quinn = "0.11.9"
rustls = "0.23.43"
rustls-platform-verifier = "0.7.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.10.9"
tokio = { version = "1.45.1", features = ["io-util", "macros", "net", "rt", "signal", "sync", "time"] }
tokio-util = "0.7.15"
tokio-rustls = "0.26.4"
url = "2.5.4"
webbrowser = "1.0.6"
winit = "0.30.13"
wry = "0.56.1"
x509-parser = "0.18.1"
zeroize = "1.8.2"
zstd = "0.13.3"
